### PR TITLE
Add PHP 8.4 support, drop PHP 8.2

### PR DESCRIPTION
**Pull request by Slamdunk**

### CODE REVIEW

**Comment by TwizzyDizzy** [comment]
Hi there,

if you have the time and the inclination, I'd very much be interested in the reasons for dropping PHP 8.2 support at this point in time. At least it does not seem to be necessitated by your upstream dependencies... at least not from the PR at hand alone.

Appreciate any hint you can give.

Cheers
Thomas

**Comment by Slamdunk** [comment]
Because I maintain more than 20 libraries in my free time and for free, so I don't care about end users that don't update their systems.

**Comment by TwizzyDizzy** [comment]
My question was neither offensive nor did it imply any kind of warranty or anything you ought to provide. I know the place your rage is coming from, yet it was not called for.

> so I don't care about end users that don't update their systems

That is your prerogative, even though you are wrong. It seems, though, that any kind of dialogue is not wanted here, so only thing left for me to do is say: have a nice day.

Cheers
Thomas

**Comment by Slamdunk** [comment]
I'm european, words don't offend me, and I don't see any rage word in my statement.

Any dialoge that involves unsupported systems needs money to flow.

**Pull request merged**
